name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "FLASK_APP=app.py" >> $GITHUB_ENV
          echo "FLASK_ENV=development" >> $GITHUB_ENV
      - name: Install Dependencies
        run: pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pytest
      - name: Run Tests
        run: pytest unit_tests.py


  run-api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start API
        run: python app.py &

  merge-to-dev:
    needs: run-api
    runs-on: ubuntu-latest
    steps:
      - name: Merge to Dev Branch
        run: |
          git checkout dev
          git merge origin/master
  deploy-to-dev:
    needs: merge-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev Environment
        run: echo "http://localhost:5000"
